# Increase command timeout
command_timeout = 5000

# Set the format for the segmented Powerline look
format = """
[](bg:none fg:#3B4252)\
$os\
$username\
[](bg:#434C5E fg:#3B4252)\
$directory\
[](fg:#434C5E bg:#4B5263)\
$git_branch\
$git_status\
[](fg:#4B5263 bg:#A3BE8C)\
$nodejs\
[](fg:#A3BE8C bg:#EBCB8B)\
$status\
[ ](fg:#EBCB8B)\
"""

# Spacing
add_newline = true

[os]
disabled = false
style = "bg:#3B4252 fg:#ECEFF4"
format = "[$symbol]($style)"

[os.symbols]
Macos = " "

[username]
show_always = true
style_user = "bg:#3B4252 fg:#88C0D0 bold"
style_root = "bg:#3B4252 fg:#BF616A bold"
format = "[$user]($style)"

[directory]
style = "bg:#434C5E fg:#E5E9F0 italic"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = " "
style = "bg:#4B5263 fg:#B48EAD italic"
format = "[ $symbol$branch ]($style)"

[git_status]
style = "bg:#4B5263 fg:#BF616A"
format = "[[($all_status$ahead_behind)]($style)]($style)"

[nodejs]
# Using text instead of glyph to avoid the "box" issue while keeping Dank Mono
symbol = "node "
style = "bg:#A3BE8C fg:#2E3440"
format = "[ $symbol($version) ]($style)"

[status]
disabled = false
style = "bg:#EBCB8B fg:#2E3440"
format = '[ $symbol $common_meaning$signal_name$maybe_int ]($style)'
map_symbol = true

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
